---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
#  - name: debian-7.x
#    driver:
#        box: debianstandard_7
#        box_url: http://vagrantimages.yrdci.fra.hybris.com/debianstandard_20150428_1258.box
#        network:
#        - ["forwarded_port", { guest: 80, host: 8181 }]
  - name: debian-8
    driver:
        box: debianstandard_8
        box_url: http://vagrantimages.yrdci.fra.hybris.com/debianstandard_8.box
#        network:
#        - ["forwarded_port", { guest: 80, host: 8181 }]

suites:
  - name: default
    run_list:
      - recipe[chef-dash::dash-prod]
      - recipe[chef-dash::repo]
    attributes: {}
    network:
    - ["forwarded_port", { guest: 80, host: 8080 }]
  - name: dash-scripts
    run_list:
      - recipe[chef-dash::dash-scripts]
    attributes: {}
    network:
    - ["forwarded_port", { guest: 80, host: 8080 }]
